# Generated by Django 3.0.3 on 2020-03-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newsletterrecipients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterRecipients',
            new_name='NewsRecipients',
        ),
    ]
